apps/cart/urls.py
from django.conf.urls import url

from apps.cart import views

urlpatterns = [
    url(r'^add$', views.CartAddView.as_view(), name='add'),
    url(r'^$', views.CartInfoView.as_view(), name='info'),
    url(r'^update$', views.UpdateCartView.as_view(), name='update'),
    url(r'^delete$', views.CartDeleteView.as_view(), name='delete')
]

apps/goods/urls.py
<<<<<<< HEAD
from django.conf.urls import url, include
=======
from django.conf.urls import url
>>>>>>> c99ace1b00b4707ae259aca0373e6e0523dae07e

from apps.goods import views

urlpatterns = [
<<<<<<< HEAD
    url(r'^index$', views.IndexView.as_view(), name='index'),
    url(r'^detail/(\d+)$', views.DetailView.as_view(), name='detail'),
    url(r'^list/(\d+)/(\d+)$', views.ListView.as_view(), name='list'),
=======
    url("^index$", views.Goods_View.as_view(), name="index"),
    url("^logout$", views.Logout_View.as_view(), name="logout"),
    url(r'^detail/(?P<sku_id>\d+)$', views.DetailView.as_view(), name='detail'),
>>>>>>> c99ace1b00b4707ae259aca0373e6e0523dae07e
]

apps/orders/urls.py
from django.conf.urls import url

from apps.orders import views

urlpatterns = [
    # /orders/place 确认订单界面
    url(r'^place$', views.PlaceOrderView.as_view(), name='place'),
    # 订单提交 /orders/commit
    url(r'^commit$', views.CommitOrderView.as_view(), name='commit'),
    # 支付接口
    url(r'^pay$', views.OrderPayView.as_view(), name='pay'),
    url(r'^check$', views.CheckPayView.as_view(), name='check'),
]

apps/users/urls.py
from django.conf.urls import url

from apps.users import views

urlpatterns = [
<<<<<<< HEAD
    # 处理登录操作
    # url(r'^do_register$', views.do_register, name='do_register'),
    url(r'^register$', views.RegisterView.as_view(), name='register'),  # 注册
    url(r'^active/(.+)$', views.ActiveView.as_view(), name='active'),  # 激活
    url(r'^login/$', views.LoginView.as_view(), name='login'),  # 登录
    url(r'^logout$', views.LogoutView.as_view(), name='logout'),  # 退出

    url(r'^address$', views.UserAddressView.as_view(), name='address'),  # 用户中心:地址
    # url(r'^orders$', views.UserOrderView.as_view(), name='orders'),  # 用户中心:订单
    url(r'^info$', views.UserInfoView.as_view(), name='info'),  # 用户中心:个人信息
    url(r'^orders/(\d+)$', views.UserOrderView.as_view(), name='orders'),  # 用户订单

=======
    # 测试
    url(r"^show_login$", views.show_login),
    url(r"^do_login$", views.do_login),
    # 注册
    url(r"^Register$", views.RegisterView.as_view(), name="Register"),
    # 激活
    url(r'^active/(.+)$', views.ActiveView.as_view(), name='active'),
    # 登陆
    url(r'^login$', views.Login_View.as_view(), name='login'),
    # 用户中心-个人信息
    url(r'^center_info$', views.Center_Info.as_view(), name='info'),
    # 用户中心-全部订单
    url(r'^center_order$', views.Center_Order.as_view(), name='order'),
    # 用户中心-收货地址
    url(r'^center_site$', views.Center_Site.as_view(), name='site'),
>>>>>>> c99ace1b00b4707ae259aca0373e6e0523dae07e
]

dailyfresh/urls.py
<<<<<<< HEAD
=======
"""dailyfresh URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
>>>>>>> c99ace1b00b4707ae259aca0373e6e0523dae07e
from django.conf.urls import include, url
from django.contrib import admin
import tinymce.urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
<<<<<<< HEAD

    url(r'^users/', include('apps.users.urls', namespace='users')),  # 用户模块
    url(r'^cart/', include('apps.cart.urls', namespace='cart')),  # 购物车模块
    url(r'^orders/', include('apps.orders.urls', namespace='orders')),  # 订单模块
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^accounts/', include('apps.users.urls')),
    url(r'^', include('apps.goods.urls', namespace='goods')),  # 商品模块
    url(r'^search/', include('haystack.urls')),


=======
    url(r'^users/', include("apps.users.urls", namespace="users")),
    url(r'^orders/', include("apps.orders.urls", namespace="orders")),
    url(r'^goods/', include("apps.goods.urls", namespace="goods")),
    url(r'^cart/', include("apps.cart.urls", namespace="cart")),
    url(r'^tinymce/', include("tinymce.urls")),
>>>>>>> c99ace1b00b4707ae259aca0373e6e0523dae07e
]

apps/cart/models.py
from django.db import models

# Create your models here.

apps/cart/views.py
<<<<<<< HEAD
from django.http import JsonResponse
from django.shortcuts import render
from django.views.generic import View
from django_redis import get_redis_connection

from apps.goods.models import GoodsSKU
from utils.LoginRequiredMixin import LoginRequiredMixin


class CartAddView(View):
    """购物车"""

    def post(self, request):
        """
        添加商品到购物车, URL: /cart/add
        :param request:
        :return:
        """
        # 判断用户是否有登录
        if not request.user.is_authenticated():
            return JsonResponse({'code': 1, 'errmsg': '请先登录'})

        # 获取用户提交的参数
        user_id = request.user.id
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # todo: 判断参数合法性
        if not all([sku_id, count]):
            return JsonResponse({'code': 2, 'errmsg': '请求参数不能为空'})
        # 检验购买数量的合法性
        try:
            count = int(count)
        except:
            return JsonResponse({'code': 3, 'errmsg': '购买数量格式不正确'})
        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'code': 4, 'errmsg': '商品不存在'})

        # todo: 业务处理: 添加商品到Redis数据库中
        # 尝试获取redis中商品的购买数量
        # cart_1: {'1':'2', '2':'2'}
        strict_redis = get_redis_connection()
        key = 'cart_%s' % user_id
        # 获取不到会返回None
        val = strict_redis.hget(key, sku_id)
        if val:
            count += int(val)

        # 校验库存是否充足
        if count > sku.stock:
            return JsonResponse({'code': 5, 'errmsg': '库存不足'})

        # 更新商品数量
        strict_redis.hset(key, sku_id, count)

        # todo: 计算购物车中商品的总数量
        cart_count = 0
        vals = strict_redis.hvals(key)
        for val in vals:  # 累加商品数量
            cart_count += int(val)
        # 响应json数据
        return JsonResponse({'code': 0, 'message': '添加到购物车成功',
                             'cart_count': cart_count})


class CartInfoView(LoginRequiredMixin, View):
    """购物车显示界面: 需要先登录才能访问"""

    def get(self, request):
        # 查询当前登录用户添加到购物车中的所有的商品
        # cart_1 = { '1': '2', '2': '2'}
        sr = get_redis_connection()
        key = 'cart_%s' % request.user.id
        # 获取购物车中所有的商品
        # {'1': '2', '2': '2'}
        my_dict = sr.hgetall(key)

        # 保存购物车中所有的商品对象
        skus = []
        # 商品总数量
        total_count = 0
        # 商品总金额
        total_amount = 0

        for sku_id, count in my_dict.items():
            # 根据商品id,查询商品对象
            sku = GoodsSKU.objects.get(id=sku_id)
            # sku对象新增一个实例属性: count
            sku.count = int(count)
            # sku对象新增一个实例属性: amount
            sku.amount = sku.price * int(count)

            # 累加总数量和总金额
            total_count += sku.count
            total_amount += sku.amount

            # 列表中新增一个商品对象
            skus.append(sku)

        # 定义模板显示的数据
        data = {
            'skus': skus,
            'total_count': total_count,
            'total_amount': total_amount,
        }

        # 响应html界面
        return render(request, 'cart.html', data)


class UpdateCartView(View):
    # /cart/update
    def post(self, request):
        """修改商品购买数量"""

        # 判断用户是否有登录
        if not request.user.is_authenticated():
            return JsonResponse({'code': 1, 'errmsg': '请先登录'})

        # 获取用户提交的参数
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 参数不能为空
        if not all([sku_id, count]):
            return JsonResponse({'code': 2, 'errmsg': '请求参数不能为空'})

        # 检验购买数量的合法性
        try:
            count = int(count)
        except Exception:
            return JsonResponse({'code': 3, 'errmsg': '购买数量格式不正确'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'code': 4, 'errmsg': '商品不存在'})

        # 库存判断
        if count > sku.stock:
            return JsonResponse({'code': 5, 'errmsg': '库存不足'})

        # todo: 业务处理: 修改redis数据库中商品的购买数量
        # cart_1 = {'1': '2', '2': '2'}
        strict_redis = get_redis_connection()
        key = 'cart_%s' % request.user.id
        # 修改hash类型中字段的值
        strict_redis.hset(key, sku_id, count)

        # todo: 计算购物车中商品的总数量
        cart_count = 0
        vals = strict_redis.hvals(key)
        for val in vals:  # 累加商品数量
            cart_count += int(val)

        # 响应请求: 返回json数据
        return JsonResponse({'code': 0, 'message': '修改商品数量成功',
                             'cart_count': cart_count})


class CartDeleteView(View):
    # /cart/delete
    def post(self, request):
        """删除购物车中的商品"""

        # 判断用户是否有登录
        if not request.user.is_authenticated():
            return JsonResponse({'code': 1, 'errmsg': '请先登录'})

        # 获取用户提交的参数
        sku_id = request.POST.get('sku_id')

        # 参数不能为空
        if not sku_id:
            return JsonResponse({'code': 2, 'errmsg': '商品id不能为空'})

        # 业务处理: 删除redis中对应的商品
        # cart_1: {'1': '2', '2': '2'}
        sr = get_redis_connection()
        key = 'cart_%s' % request.user.id
        # 删除hash中的一个字段和值: hdel
        sr.hdel(key, sku_id)

        # 响应请求,返回json数据
        return JsonResponse({'code': 0, 'message': '删除商品成功'})
=======
from django.shortcuts import render

# Create your views here.
>>>>>>> c99ace1b00b4707ae259aca0373e6e0523dae07e

templates/base_no_cart.html
{# 搜索栏中没有购物车信息显示:购物车界面,确认订单界面,用户信息界面 #}
{% extends 'base.html' %}

{% load staticfiles %}

{# 重写父类搜索栏: 去掉购物车栏 #}
{% block search_bar %}
    <div class="search_bar clearfix">
        <a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
        <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{% block page_title %}{% endblock %}</div>
        <form method="get" action="/search">
            <div class="search_con fl">

                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">

            </div>
        </form>
    </div>
{% endblock %}

templates/base_user_center.html
{# 用户中心父模板: 用户中心的3个子界面 #}
{% extends 'base_no_cart.html' %}

{% block title %}
    天天生鲜-用户中心
{% endblock %}

{% block page_title %}
    用户中心
{% endblock %}

{% block body %}
    <div class="main_con clearfix">
        {# 左侧部分内容 #}
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="{% url 'users:info' %}" {% if which_page == 1 %}
                       class="active"
                {% endif %} >· 个人信息</a></li>

                <li><a href="{% url 'users:orders' 1 %}" {% if which_page == 2 %}
                       class="active"
                {% endif %}>· 全部订单</a></li>

                <li><a href="{% url 'users:address' %}" {% if which_page == 3 %}
                       class="active"
                {% endif %}>· 收货地址</a></li>
            </ul>
        </div>

        {# 右侧部分内容 #}
        {% block right_body %}
        {% endblock %}

    </div>
{% endblock %}

templates/user_center_info.html
<<<<<<< HEAD
{% extends 'base_user_center.html' %}
{% block right_body %}
=======
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>天天生鲜-用户中心</title>
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/main.css">
</head>
<body>
<div class="header_con">
    <div class="header">
        <div class="welcome fl">欢迎来到天天生鲜!</div>
        <div class="fr">
            {% if user.is_authenticated %}
                <div class="login_btn fl">
                    欢迎您：<em>{{ user.username }}</em>
                    <span>|</span>
                    <a href="{% url 'goods:logout' %}">退出</a>
                </div>
            {% else %}
                <div class="login_btn fl">
                    <a href="{% url 'users:login' %}">登录</a>
                    <span>|</span>
                    <a href="{% url 'users:Register' %}">注册</a>
                </div>
            {% endif %}
            <div class="user_link fl">
                <span>|</span>
                <a href={% url "users:info" %}>用户中心</a>
                <span>|</span>
                <a href="cart.html">我的购物车</a>
                <span>|</span>
                <a href="user_center_order.html">我的订单</a>
            </div>
        </div>
    </div>
</div>

<div class="search_bar clearfix">
    <a href={% url "goods:index" %} class="logo fl"><img src="/static/images/logo.png"></a>
    <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
    <div class="search_con fr">
        <input type="text" class="input_text fl" name="" placeholder="搜索商品">
        <input type="button" class="input_btn fr" name="" value="搜索">
    </div>
</div>

<div class="main_con clearfix">
    <div class="left_menu_con clearfix">
        <h3>用户中心</h3>
        <ul>
            <li><a href={% url "users:info" %} {% if page == 1 %}
                class="active"
            {% endif %}>· 个人信息</a></li>
            <li><a href={% url "users:order" %}>· 全部订单</a></li>
            <li><a href={% url "users:site" %}>· 收货地址</a></li>
        </ul>
    </div>
>>>>>>> c99ace1b00b4707ae259aca0373e6e0523dae07e
    <div class="right_content clearfix">
        <div class="info_con clearfix">
            <h3 class="common_title2">基本信息</h3>
            <ul class="user_info_list">
<<<<<<< HEAD
                <li><span>用户名：</span>{{ user.username }}</li>
                <li><span>联系方式：</span>{{ address.receiver_mobile }}</li>
                <li><span>联系地址：</span>{{ address.detail_addr }}</li>
            </ul>
        </div>


        <h3 class="common_title2">最近浏览</h3>
        <div class="has_view_list">
            <ul class="goods_type_list clearfix">

                {% for sku in skus %}
                    <li>
                        <a href={% url 'goods:detail' sku.id %}>><img src="{{ sku.default_image.url }}"></a>
                        <h4><a href={% url 'goods:detail' sku.id %}>{{ sku.id }}.{{ sku.name }}</a></h4>
                        <div class="operate">
                            <span class="prize">￥{{ sku.price }}</span>
                            <span class="unit">￥{{ sku.price }}/{{ sku.unit }}</span>
=======
                {% if address %}
                    <li><span>用户名：</span>{{ address.receiver_name }}</li>
                    <li><span>联系方式：</span>{{ address.receiver_mobile }}</li>
                    <li><span>联系地址：</span>{{ address.detail_addr }}</li>
                {% else %}
                    <li>无</li>
                {% endif %}
            </ul>
        </div>

        <h3 class="common_title2">最近浏览</h3>
        <div class="has_view_list">
            <ul class="goods_type_list clearfix">
                {% for sku in skus %}
                    <li>
                        {#商品图片显示#}
                        <a href={% url "goods:detail" sku.id %}><img src={{ sku.default_image.url }}></a>
                        <h4><a href="detail.html">{{ sku.id }}.{{ sku.name }}</a></h4>
                        <div class="operate">
                            <span class="prize">￥{{ sku.price }}</span>
                            <span class="unit">{{ sku.price }}/{{ sku.unit }}</span>
>>>>>>> c99ace1b00b4707ae259aca0373e6e0523dae07e
                            <a href="#" class="add_goods" title="加入购物车"></a>
                        </div>
                    </li>
                {% endfor %}
<<<<<<< HEAD

            </ul>
        </div>
    </div>
{% endblock %}
=======
            </ul>
        </div>
    </div>
</div>


<div class="footer">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
    <p>电话：010-****888 京ICP备*******8号</p>
</div>

</body>
</html>
>>>>>>> c99ace1b00b4707ae259aca0373e6e0523dae07e

templates/user_center_order.html
<<<<<<< HEAD
{% extends 'base_user_center.html' %}

{% block right_body %}
    {% csrf_token %}
    <div class="right_content clearfix">
        <h3 class="common_title2">全部订单</h3>

        {% for order in page %}
            <ul class="order_list_th w978 clearfix">
                <li class="col01">{{ order.create_time }}</li>
                <li class="col02">订单号：{{ order.order_id }}</li>
                <li class="col02 stress">{{ order.status_desc }}</li>
            </ul>
            <table class="order_list_table w980">
                <tbody>
                <tr>
                    <td width="55%">
                        {% for order_sku in order.order_skus %}
                            <ul class="order_goods_list clearfix">
                                <li class="col01">
                                    <img src="{{ order_sku.sku.default_image.url }}">
                                </li>
                                <li class="col02">{{ order_sku.sku.name }}
                                    <em>{{ order_sku.sku.price }}元/
                                        {{ order_sku.sku.unit }}</em>
                                </li>
                                <li class="col03">{{ order_sku.count }}</li>
                                <li class="col04">{{ order_sku.amount }}元</li>
                            </ul>
                        {% endfor %}

                    </td>
                    <td width="15%">{{ order.total_pay }}元</td>
                    <td width="15%">{{ order.status_desc }}</td>
                    <td width="15%"><a href="#"
                                       order_id="{{ order.order_id }}"
                                       status="{{ order.status }}"
                                       class="oper_btn">
                                        {{ order.status_desc }}</a></td>
                </tr>
                </tbody>
            </table>
        {% endfor %}

        <div class="pagenation">
            {% if page.has_previous %}
                <a href="{% url 'users:orders' page.previous_page_number %}">
                    <上一页
                </a>
            {% endif %}
            {% for index in page_range %}
                {% if index == page.number %}
                    <a href="{% url 'users:orders' index %}"
                       class="active">{{ index }}</a>
                {% else %}
                    <a href="{% url 'users:orders' index %}">{{ index }}</a>
                {% endif %}
            {% endfor %}

            {% if page.has_next %}
                <a href="{% url 'users:orders' page.next_page_number %}">
                    下一页></a>
            {% endif %}
        </div>

    </div>
{% endblock %}

{% block bottom_js %}
    {% load staticfiles %}
    {% csrf_token %}

    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script>

        // 获取订单状态, 再刷新订单操作按钮显示的文本
        var status = $('.oper_btn').attr('status');
        if (status == 1) {
            $('.oper_btn').text('待支付');
        } else if (status == 4) {
            $('.oper_btn').text('去评论');
        } else if (status == 5) {
            $('.oper_btn').text('已完成');
        }

        // 点击去付款
        $('.oper_btn').click(function () {
            var status = $(this).attr('status');
            var order_id = $(this).attr('order_id');
            var csrf = $('input[name="csrfmiddlewaretoken"]').val();

            // alert(order_id+":"+status);
            if (status == 1) { // 待支付,才需要调起支付宝支付
                // 定义post请求参数
                var params = {
                    'order_id': order_id,
                    'csrfmiddlewaretoken': csrf
                };

                // 发起post请求
                $.post('/orders/pay', params, function (data) {
                    if (data.code == 0) { // 请求成功
                        // 打开支付宝支付界面, 输入支付宝账号密码进行支付
                        window.open(data.pay_url);

                        // 查询支付结果
                        $.post('/orders/check', params, function (data) {
                            if (data.code == 0) {  // 支付成功
                                alert('订单支付成功');
                                // 重新加载当前界面,刷新订单状态显示
                                window.location.reload();
                            } else {
                                // 支付失败
                                alert('订单支付失败');
                            }
                        })
                    } else {
                        alert(data.errmsg);
                    }
                })
            }
        })
    </script>

{% endblock %}

=======
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-用户中心</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				  {% if user.is_authenticated %}
                    <div class="login_btn fl">
                        欢迎您：<em>{{ user.username }}</em>
                        <span>|</span>
                        <a href="{% url 'goods:logout' %}">退出</a>
                    </div>
                  {% else %}
                    <div class="login_btn fl">
                        <a href="{% url 'users:login' %}">登录</a>
                        <span>|</span>
                        <a href="{% url 'users:Register' %}">注册</a>
                    </div>
                  {% endif %}
                    <div class="user_link fl">
                        <span>|</span>
                        <a href={% url "users:info" %}>用户中心</a>
                        <span>|</span>
                        <a href="cart.html">我的购物车</a>
                        <span>|</span>
                        <a href="user_center_order.html">我的订单</a>
                    </div>
            </div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href={% url "goods:index" %} class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href={% url "users:info" %}>· 个人信息</a></li>
				<li><a href={% url "users:order" %} {% if page %}
			class="active"
			{% endif %}>· 全部订单</a></li>
				<li><a href={% url "users:site" %}>· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
				<ul class="order_list_th w978 clearfix">
					<li class="col01">2016-8-21 17:36:24</li>
					<li class="col02">订单号：56872934</li>
					<li class="col02 stress">未支付</li>		
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="/static/images/goods02.jpg"></li>
									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>	
									<li class="col03">1</li>
									<li class="col04">11.80元</li>	
								</ul>
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="/static/images/goods02.jpg"></li>
									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>	
									<li class="col03">1</li>
									<li class="col04">11.80元</li>	
								</ul>
							</td>
							<td width="15%">33.60元</td>
							<td width="15%">待付款</td>
							<td width="15%"><a href="#" class="oper_btn">去付款</a></td>
						</tr>
					</tbody>
				</table>
				
				<ul class="order_list_th w978 clearfix">
					<li class="col01">2016-8-21 17:36:24</li>
					<li class="col02">订单号：56872934</li>
					<li class="col02 stress">已支付</li>			
				</ul>
				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="/static/images/goods02.jpg"></li>
									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>	
									<li class="col03">1</li>
									<li class="col04">11.80元</li>	
								</ul>
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="/static/images/goods02.jpg"></li>
									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>	
									<li class="col03">1</li>
									<li class="col04">11.80元</li>	
								</ul>
							</td>
							<td width="15%">33.60元</td>
							<td width="15%">已付款</td>
							<td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
						</tr>
					</tbody>
				</table>

				<div class="pagenation">
					<a href="#"><上一页></上一页></a>
					<a href="#" class="active">1</a>
					<a href="#">2</a>
					<a href="#">3</a>
					<a href="#">4</a>
					<a href="#">5</a>
					<a href="#">下一页></a>
				</div>
		</div>
	</div>



	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>
>>>>>>> c99ace1b00b4707ae259aca0373e6e0523dae07e